#################
# General Setting
#################
# Experiment name, if the experiment name has the word debug, it will enter debug mode
name: FSIL_TOPIC_res18_CUB_SoftNet0.86_aug_lr2e-3_clr2e-3_s140_m500_700_4600
#name: FSIL_TOPIC_res18_CUB_SoftNet0.60_aug_lr2e-2_clr2e-2_s140_m400_600_p1_g2_alice
# The type of model used, usually the class name of the model defined in the `methods` directory
model_type: WSNBaseTopicModel
subnet_type: softnet
# gpu
gpu: 0
# Random seed
manual_seed: 1997
Random: false

#################################
# The settings for the dataset and data loader
#################################
transformer_agu:
  - type: RandomResizedCrop
    size: 224
  - type: ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
  - type: RandomHorizontalFlip
  - type: ToTensor
  - type: Normalize
    mean: !!python/tuple [0.485, 0.456, 0.406]
    std: !!python/tuple [0.229, 0.224, 0.225]

transformer:
  - type: Resize
    size: 256
  - type: CenterCrop
    size: 224
  - type: ToTensor
  - type: Normalize
    mean: !!python/tuple [ 0.485, 0.456, 0.406 ]
    std: !!python/tuple [ 0.229, 0.224, 0.225 ]


datasets:
  # The important information of dataset
  train:
    name: cub200
    type: NormalDataset
    total_classes: 200
    dataroot: DataSet
    aug: true
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 4
    # Batch size
    batch_size_base_classes: 256
    pin_memory: true
    pre_load: false

    sampler: 
      type: TaskSampler
      num_samples: 8

  val:
    name: cub200
    type: NormalDataset
    total_classes: 200
    dataroot: DataSet
    aug: false
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 4
    pre_load: false
    sampler:
      type: ~

#####################
# The following is the setup of the network structure
#####################
network_g:
  type: SigResnet18_small_v2
  num_classes: 100
  adopt_classifier: true
  flatten: true
  sparsity: 0.14
  gamma: 1.0
  conv1_kernel: 7

######################################
# The following are the paths
######################################
path:
  # Pre-trained subnet model path, need models ending in pth
  #pretrain_model_g: ./exp/cub_bases1000/subnet-fc_c0.001_bs512_Adam_lr0.001/checkpoints/last.pth
  #pretrain_model_g: ./exp/cub_bases1000/subnet-2gpus-fc_c0.001_bs512_Adam_lr0.001/checkpoints/last.pth

  #pretrain_model_g: ./exp/cub_bases1000/subnet-2gpus-all-fc_c0.001_bs512_Adam_lr0.001_alpha1.0/checkpoints/last.pth

  pretrain_model_g: ./exp/cub_bases1000/subnet-2gpus-all-fc_c0.001_bs512_Adam_lr0.001_alpha1.0/checkpoints/last_v1.pth
  

  # Whether to load pretrained models strictly, that is the corresponding parameter names should be the same
  strict_load: false
  #
  resume_state: ~

#################
# The following is the training setup
#################
train:
  # Optimizer
  optim_g:
    # The type of optimizer
    type: SGD
    # learning rate
    lr: !!float 2e-3
    lr_cf: !!float 2e-3 
    weight_decay: !!float 5e-4
    # momentum
    momentum: !!float 0.9

  # The setting of scheduler
  scheduler:
    # The type of scheduler
    type: MultiStepLR
    #### The following properties are flexible, depending on the learning rate Scheduler has different settings
    # milestones
    #milestones: [!!python/object/apply:eval [ 400 * 1 ],
    #             !!python/object/apply:eval [ 600 * 3 ],
    #             !!python/object/apply:eval [ 700 * 3 ]
    #             ]
   
    #milestones: [!!python/object/apply:eval [ 600 * 3 ],
    #             !!python/object/apply:eval [ 900 * 3 ]]

    milestones: [!!python/object/apply:eval [ 500 * 3 ],
                 !!python/object/apply:eval [ 700 * 3 ],
                 !!python/object/apply:eval [ 4600 * 1 ],
    ]
    # gama
    gamma: 0.1

  # The number of epoch
  epoch: 600
  s_epoch: 140 #550 start smoothing
  # The number of warm up iteration, if -1, means no warm up
  warmup_iter: -1  # no warm up
  # number of base classes
  bases: 100
  # number of tasks for incremental few-shot learning
  tasks: 11

#######################
# The following are the settings for Validation
#######################
val:
  # The frequency of validation
  val_freq: 200

####################
# The following are the settings for Logging
####################
logger:
  # Frequency of loggers printed on the screen according to iteration
  print_freq: 10
  # 保存checkpoint的频率
  save_checkpoint_freq: 15000
  # Whether to use tensorboard logger

  use_tb_logger: true
  # Whether to use wandb logger
  wandb:
    # The default is None, i.e. wandb is not used.
    project: FSIL-TOPIC-CUB-100bases
    # If it is resume, you can enter the last wandb id, then the log can be connected
    resume_id: ~

